feat: add schema docs
sdkgen/sdkgen.github.io pull request #16
Opened 2020-03-23 18:04 UTC by thiagoarmede

Adding schema definition instructions!

Need help:
Reordering docz menu (intro sticks below "Defining your schema" menu :cry:)

2020-03-23 18:11 UTC, lbguilherme requested changes

2020-03-23 18:11 UTC, lbguilherme commented on defining-your-schema.mdx
> +    Sao_Paulo
What is this casing schema?

2020-03-23 18:11 UTC, lbguilherme commented on defining-your-schema.mdx
> +// Sending arguments on path adn querystring.
"and"

2020-03-23 18:11 UTC, lbguilherme commented on defining-your-schema.mdx
> +* `cnpj` - companies document number.
company document number.

2020-03-23 18:17 UTC, lbguilherme commented
You can create "doczrc.js". See here: https://www.docz.site/docs/project-configuration

2020-03-23 18:28 UTC, dgadelha requested changes

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +* `cnpj` - company document number.
```suggestion
* `uint` - an unsigned integer
* `void` - the absence of any value
* `date` - a simple RFC date type
* `datetime` - full date type, with time included, always converted to UTC
* `bytes` - a byte buffer, commonly used when uploading files
* `money` - an integer for representing money in cents
* `bigint` - a way to represent integers bigger than 2^53
* `email` - an email address valid value
* `hex` - an hexadecimal number.
* `base64` - encoding format for transferring data via text
* `url` - [URL](https://www.w3.org/Addressing/URL/url-spec.txt)
* `xml` - [XML](https://www.w3.org/TR/xml/)
* `json` - [JSON](https://www.json.org/json-pt.html)

Brazilian utility types:

* `cpf` - personal document number
* `cnpj` - company document number
```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +To compose types into more complex ones, sdkgen provides a typescript-like syntax:
```suggestion
To compose types into more complex ones, sdkgen provides a TypeScript-like syntax:
```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +
```suggestion

```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +
```suggestion

```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +
```suggestion

```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +    type: enum {Teacher Student Director}
```suggestion
    type: enum { Teacher Student Director }
```

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +```
We could add some real use cases here instead of `X`, `Y`, `bla` and `foo`

2020-03-23 18:28 UTC, dgadelha commented on defining-your-schema.mdx
> +
```suggestion

```

2020-03-23 18:45 UTC, lbguilherme commented on defining-your-schema.mdx
> +* `json` - [JSON](https://www.json.org/json-pt.html)
https://www.json.org/json-en.html

2020-03-23 18:45 UTC, lbguilherme commented on defining-your-schema.mdx
> +* `base64` -  encoding format for transfering data via text
```suggestion
* `base64` - encoding format for transfering data via text
```

2020-03-23 23:56 UTC, lbguilherme approved these changes

2020-03-24 17:36 UTC, dgadelha approved these changes

2020-03-24 17:37 UTC, merged